name: agentgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - ca-certificates=2024.2.2
  - ipython=8.12.0
  - ipykernel=6.29.3
  - jupyter_client=7.3.4
  - jupyter_core=5.5.0
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - scipy=1.12.0
  - scikit-learn=1.5.0
  - psutil=5.9.0
  - pygments=2.17.2
  - tornado=6.1
  - traitlets=5.14.2
  - setuptools=68.2.2
  - wheel=0.41.2
  - typing_extensions=4.10.0
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - nest-asyncio=1.6.0
  - parso=0.8.3
  - jedi=0.19.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pure_eval=0.2.2
  - six=1.16.0
  - stack_data=0.6.2
  - wcwidth=0.2.13
  - decorator=5.1.1
  - executing=2.0.1
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cryptography==42.0.5
      - cycler==0.12.1
      - datasets==2.18.0
      - dill==0.3.8
      - distro==1.9.0
      - exceptiongroup==1.2.0
      - filelock==3.13.3
      - fire==0.5.0
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gensim==4.3.3
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - idna==3.6
      - imageio==2.34.0
      - importlib-metadata==7.0.2
      - importlib-resources==6.1.3
      - joblib==1.3.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - lazy-loader==0.3
      - msal==1.27.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - nltk==3.8.1
      - openai==1.13.3
      - packaging==23.2
      - pillow==9.5.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pycparser==2.21
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.3
      - scikit-image==0.22.0
      - smart-open==7.0.4
      - sniffio==1.3.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.2.12
      - tokenizers==0.19.1
      - tqdm==4.66.2
      - transformers==4.42.3
      - tzdata==2024.1
      - urllib3==2.2.1
      - wordcloud==1.9.3
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.17.0
